### PR TITLE
chore: add codeql-analysis workflow

### PR DESCRIPTION
**Pull request by freelancing-solutions**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-datastore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by freelancing-solutions** [comment]
@googlebot I signed it!

**Comment by freelancing-solutions** [comment]
## Added codeql security analysis github workflow to the repository.

**Comment by tseaver** [comment]
@freelancing-solutions Thanks for the patch!  We are discussing the implications of adding CodeQL to this repository (and likely others).  I'm not personally familiar with the tool:  can you describe your motivation for wanting to add it?

**Comment by tseaver** [comment]
@freelancing-solutions Again, thank you for the patch, and for bringing the CodeQL tool to our attention.  For such process-related / CI chores, the team prefers to discuss them and then add them broadly, across most / all the `googleapis` repos, using the autosynth tools we have built.

**Pull request closed without merging**
