### PR TITLE
feat: add synth config to generate datastore_admin_v1

### PR DESCRIPTION
**Pull request by AVaksman**

### CODE REVIEW

**Comment by AVaksman** [comment]
For this feature to work properly a small fix in https://github.com/googleapis/googleapis/pull/600 needs to be merged first.

**Comment by crwilcox** [comment]
@AVaksman have you tested the generation of this and that it works locally?

**Comment by crwilcox** [comment]
```
2020-06-15 15:13:56,876 synthtool > Ensuring dependencies.
2020-06-15 15:13:57,321 synthtool > Cloning googleapis.
2020-06-15 15:13:59,623 synthtool > Generating code for: //google/datastore/v1:datastore-v1-py.
2020-06-15 15:14:02,072 synthtool > Failed executing bazel --max_idle_secs=60 build //google/datastore/v1:datastore-v1-py:

Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /Users/crwilcox/.cache/synthtool/googleapis/.bazelrc:
  'build' options: --protocopt=--include_source_info --protocopt=--experimental_allow_proto3_optional --enable_platform_specific_config
ERROR: Unrecognized option: --enable_platform_specific_config
INFO: Invocation ID: 23e865cf-b7f4-4135-87b5-50f8bc963407

2020-06-15 15:14:02,074 synthtool > Wrote metadata to synth.metadata.
Traceback (most recent call last):
  File "/Users/crwilcox/.pyenv/versions/3.8.2/bin/synthtool", line 10, in <module>
    sys.exit(main())
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/synthtool/__main__.py", line 94, in main
    spec.loader.exec_module(synth_module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/crwilcox/workspace/googleapis/python-datastore/synth.py", line 25, in <module>
    library = gapic.py_library(
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/synthtool/gcp/gapic_bazel.py", line 46, in py_library
    return self._generate_code(service, version, "python", **kwargs)
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/synthtool/gcp/gapic_bazel.py", line 180, in _generate_code
    shell.run(bazel_run_args)
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/synthtool/shell.py", line 39, in run
    raise exc
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/site-packages/synthtool/shell.py", line 27, in run
    return subprocess.run(
  File "/Users/crwilcox/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bazel', '--max_idle_secs=60', 'build', '//google/datastore/v1:datastore-v1-py']' returned non-zero exit status 2.
```

**Comment by crwilcox** [comment]
Locally was able to generate it seems so approving this.

**Pull request merged**
