### PR TITLE
chore: use gcp-sphinx-docfx-yaml for docfx

### PR DESCRIPTION
**Pull request by busunkim96**

### CODE REVIEW

**Review by tseaver — APPROVED** [review]
The readme for the `gcp-sphinx-docfx-yaml` repository says "for personal or experimental use", but I guess since we control it, we can live with that.

BTW, why was that repo created de-novo, instead of Github-forking the docascode version?

**Comment by busunkim96** [comment]
> BTW, why was that repo created de-novo, instead of Github-forking the docascode version?

Hrm it might not be listed as a fork because of the internal repo creation process. Perhaps `googleapis` doesn't let you create new repos through the GItHub UI? I think it was intended to be a fork though. @dandhlee? 

The main issue we had with `sphinx-docfx-yaml` was that it [pins to an old specific version of sphinx](https://github.com/docascode/sphinx-docfx-yaml/blob/23b4cd46c3e52d271be01647155e7164863fdafd/setup.py#L7)

**Comment by dandhlee** [comment]
For it to be under `googleapis` it needed to go through the internal release process, which does make it look like a standalone product/repository rather than a fork.

**Comment by busunkim96** [comment]
@googleapis/firestore-dpe Friendly ping

**Comment by dandhlee** [comment]
closing this as #161 was already merged

**Pull request closed without merging**
