### PR TITLE
feat(datastore): add missing method for system test with emulator

### PR DESCRIPTION
**Pull request by HemangChothani**
Towards [bigtable-5](https://github.com/googleapis/python-bigtable/issues/5)

### CODE REVIEW

**Comment by crwilcox** [comment]
Where is the code that uses this?

**Comment by HemangChothani** [comment]
Here method has called but implementation was not there. 
https://github.com/googleapis/python-datastore/blob/96fd5b812c856b5d0d71d5cfe8e72a6e8795858c/tests/system/test_system.py#L252-L256

**Comment by crwilcox** [comment]
Have you validated this locally, or would this run in ci? I ask as delete_multi can only take so many keys at once.

**Comment by HemangChothani** [comment]
I have validate locally, it works fine and delete all the keys.

**Pull request merged**
